

Server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
          show_sql: true
          format_sql: true
          ddl-auto: update

  logging:
    level:
      org:
        hibernate:
          type: trace
